name: practica_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:
  equatable:
  local_auth:
  flutter_credit_card:
  image_picker:
  share:
  screenshot:
  path_provider:
  share_plus_web: ^2.0.4
  shared_preferences_web: ^2.0.3
  feature_discovery:
  provider: ^6.0.2
  backdrop: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
